services:
  traefik:
    image: traefik:v3.5
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic:/etc/traefik/dynamic
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped
    networks:
      - traefik_proxy
      - nextcloud-aio

networks:
  traefik_proxy:
    external: true
  nextcloud-aio:
    external: true
