entryPoints:
  web:
    address: ":80"
  https:
    address: ":443"

api:
  dashboard: false
  insecure: false

log:
  level: DEBUG

certificatesResolvers:
  letsencrypt:
    acme:
      email: "easttem@gmail.com"
      storage: /letsencrypt/acme.json
      tlsChallenge: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

  swarm:
    # endpoint: "tcp:///127.0.0.1:2377"
    endpoint: "unix:///var/run/docker.sock"
    watch: true

  file:
    directory: "/etc/traefik/dynamic"
    watch: true
