services:
  agent:
    image: portainer/agent
    container_name: portainer_agent
    environment:
      AGENT_CLUSTER_ADDR: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - wg_network
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - "10000:9000"
      - "9000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - wg_network
    depends_on:
      - agent
    restart: unless-stopped

networks:
  wg_network:
    external: true

volumes:
  portainer_data:
