services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "12443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vps-network
    restart: unless-stopped

networks:
  vps-network:
    external: true

volumes:
  portainer_data:
