services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "12443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  portainer_data:
